### ISSUE TITLE
ipython notebooks aren't included

### ISSUE THREAD

**Issue by ericzinn** [yesimon/myoaav_capsid#1]
I think your included ipython notebooks are just symbolic links.  Sweet vectors btw.

**Comment by dgoswamia** [comment]
Hello Simon, 
I agree great vector design, but unable to see your notebook scripts
Notebook
/home/yesimon/src/aav_capsid/notebooks/hFXN QC.ipynb
/home/yesimon/src/aav_capsid/notebooks/MyoAAV Paper Figures.ipynb

Please reupload them. 
Thanks

**Comment by yesimon** [comment]
Sorry about that. Fixed in 2a51a3a.

**Comment by dgoswamia** [comment]
Thank You!! Simon for update on notebook
